use ELMA
go
create table dbo.Users(
		UserID INT IDENTITY(1,1) NOT NULL,
		UserName NVARCHAR(50) NOT NULL,
		UserPassword NVARCHAR(50) NOT NULL
CONSTRAINTS [dbo.Users] PRIMARY KEY CLUSTERED
(
	[UserID] ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON)
) ON [PRIMARY]
